### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by Kevin-com** [mmaheo/weather-swiftui#1]
Hello, when i try to launch the app on my iPhone. xCode give's an error:
/Users/kevin/App/weather-swiftui-master/Pods/Target Support Files/Pods-Weather/Pods-Weather.debug.xcconfig: unable to open file (in target "Weather" in project "Weather")
Unable to load contents of file list: '/Target Support Files/Pods-Weather/Pods-Weather-frameworks-Debug-input-files.xcfilelist'

Are there any files missing?

Thank you!

**Comment by akinoavx13** [comment]
Hi ! Thank you to run my project !
I've forgot to tell people to run `pod install` to install cocoapods dependencies ...
So go in your root directory and run this comand (install cocoapods if you don't have it)
Tell me if you have trouble to install dependencies,

Maxime

**Comment by Kevin-com** [comment]
> Hi ! Thank you to run my project !
> I've forgot to tell people to run `pod install` to install cocoapods dependencies ...
> So go in your root directory and run this comand (install cocoapods if you don't have it)
> Tell me if you have trouble to install dependencies,
> 
> Maxime

Thank you Maxime!
